version: '3.9'
services:
  frontend:
      build: ./frontend
      ports:
        - 3000:3000
      platform: linux/x86_64
      working_dir: /app-frontend
      depends_on:
        backend:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "lsof", "-t", "-i:3000"]
        timeout: 10s
        retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    command: sh -c "npm run db:reset && npm start"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=postgres
      - DB_PASS=example
      - DB_HOST=db
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s