version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s